version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    image: XXX/act1-backend:latest
    container_name: backend_api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/points_db
      PORT: 5000
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: XXX/act1-frontend:latest
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: 